/* eslint-disable react-refresh/only-export-components */
import { createFileRoute } from '@tanstack/react-router'
import { TaskForm } from '../components/TaskForm'
import { TaskQueue } from '../components/TaskQueue'
import { useState } from 'react'

// @ts-ignore - Route path will be generated by TanStack Router plugin
export const Route = createFileRoute('/sprint-planner')({
  component: SprintPlannerPage,
})

export interface Task {
  id?: string
  title: string
  description: string
  assignedAgent: string
  priority: 'low' | 'medium' | 'high'
  dueDate: string
}

function SprintPlannerPage() {
  const [refreshKey, setRefreshKey] = useState(0)

  const handleTaskCreated = () => {
    setRefreshKey((prev) => prev + 1)
  }

  return (
    <main className="min-h-screen bg-slate-900 text-white p-8">
      <div className="max-w-7xl mx-auto">
        <h1 className="text-3xl font-bold mb-8">Sprint Planner</h1>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Form Section */}
          <div className="lg:col-span-1">
            <div className="bg-slate-800 rounded-lg p-6">
              <h2 className="text-xl font-semibold mb-6">Create Task</h2>
              <TaskForm onTaskCreated={handleTaskCreated} />
            </div>
          </div>

          {/* Task Queue Section */}
          <div className="lg:col-span-2">
            <div className="bg-slate-800 rounded-lg p-6">
              <h2 className="text-xl font-semibold mb-6">Task Queue</h2>
              <TaskQueue key={refreshKey} />
            </div>
          </div>
        </div>
      </div>
    </main>
  )
}
