/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SprintPlannerRouteImport } from './routes/sprint-planner'
import { Route as IndexRouteImport } from './routes/index'

const SprintPlannerRoute = SprintPlannerRouteImport.update({
  id: '/sprint-planner',
  path: '/sprint-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sprint-planner': typeof SprintPlannerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sprint-planner': typeof SprintPlannerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sprint-planner': typeof SprintPlannerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sprint-planner'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sprint-planner'
  id: '__root__' | '/' | '/sprint-planner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SprintPlannerRoute: typeof SprintPlannerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sprint-planner': {
      id: '/sprint-planner'
      path: '/sprint-planner'
      fullPath: '/sprint-planner'
      preLoaderRoute: typeof SprintPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SprintPlannerRoute: SprintPlannerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
